### ISSUE TITLE
Can not set custom build path.

### ISSUE THREAD

**Issue by joemorin73** [Dinomite-Studios/unity-azure-pipelines-tasks#100]
I'm using v2.* and my tasks are failing with as follows:

    Unity process has finished. Checking for build output in C:\agent\_work\1\s\Build\WebGL
     ##[error]The Unity build task finished without results. Check editor logs for details.

I know the problem.  In my buildscript, I'm setting the build output to the DevOps build folder.

    string destinationPath = String.Empty + Environment.GetEnvironmentVariable("BUILD_BINARIESDIRECTORY");

Is there anyway to explicitly direct the task to monitor the correct folder?

**Comment by FejZa** [comment]
Hi @joemorin73, could you please try Unity Build V3 Preview? It's released in the marketplace and you manually need to update the task version in your pipeline. V3 lets you specify where to output files.

**Comment by FejZa** [comment]
This is resolved in v2.7 with Build Task V3.
