### ISSUE TITLE
Android Signing

### ISSUE THREAD

**Issue by devedse** [Dinomite-Studios/unity-azure-pipelines-tasks#101]
Would it be possible to add Android APK Signing to the build task?

The required keystore / key alias / passwords can be passed to the Android player settings:
https://answers.unity.com/questions/731422/how-to-sign-apks-for-publish-when-using-buildpipel.html

Ideally this would be implemented using the SecureFiles like in this task:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=azure-devops

That way you can provide a keystore file through the UI:
![image](https://user-images.githubusercontent.com/2350015/64494820-c04eee80-d291-11e9-8679-284db777ee9e.png)

The Android Signer that I used in the example here doesn't really work well. It's probably better to be able to do this straight from Unity

**Comment by FejZa** [comment]
Hi @devedse, I am using the above signing and aligning task myself. What issues are you running into? I'd rather not bloat the build task itself further since there is a separate task for it.

**Comment by devedse** [comment]
@FejZa , adding to the previous comment. I've now been able to sign my apk manually using some powershell scripts.

However, when I now upload the APK to the play store I still get a warning that it's not bundled as an AppBundle. (Basically the setting I mentioned above). Do you know if there's an alternative for that?

(Also, if you have an idea why the App Signing fails for me, let me know)

**Comment by FejZa** [comment]
Closing this, since unrelated to this extension.
