### ISSUE TITLE
Warning: User declined to install module (UnitySetup)

### ISSUE THREAD

**Issue by Yecats** [Dinomite-Studios/unity-azure-pipelines-tasks#103]
I'm encountering an issue with the UnitySetup step with the Microsoft hosted build. The output I am getting is "WARNING: User declined to install module (UnitySetup)."

![image](https://user-images.githubusercontent.com/4108756/64911963-2944c500-d6dd-11e9-9f60-28b1107771f8.png)

Anyone know how to fix this?

The next job is failing, I believe as a result of this first error, with "Find-UnitySetupInstaller : The term 'Find-UnitySetupInstaller' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

![image](https://user-images.githubusercontent.com/4108756/64912078-e5eb5600-d6de-11e9-9222-05691668b0b4.png)

**Comment by cpetry** [comment]
If others stumple across this:
I got it running by added "-Force" to the PowerShell script
