### ISSUE TITLE
Hosted Agent Unity Pro question 

### ISSUE THREAD

**Issue by Nemikolh** [Dinomite-Studios/unity-azure-pipelines-tasks#107]
Hi, I haven't been able to find any information about why a unity free license can't be used on a hosted agent.

I have been looking at the Unity documentation [here](https://docs.unity3d.com/Manual/CommandLineArguments.html) but there is no mention of a unity pro license restriction. 

Is this a limitation of the plugin? Or maybe the doc is outdated?

Many thanks.

**Comment by Nemikolh** [comment]
Hi @FejZa, thanks a lot for your message. So I have encountered the same issue as you said, which is that the license activation from Unity seems to mandate a serial key. (unless it's a bug, but I couldn't find any open ticket)

However, I also found out that the UI allow for manual activation and generate an xml file like this one:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <SystemInfo>
        <IsoCode>en</IsoCode>
        <UserName>...</UserName>
        <OperatingSystem>linux</OperatingSystem>
        <OperatingSystemNumeric></OperatingSystemNumeric>
        <ProcessorType>Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz</ProcessorType>
        <ProcessorSpeed>4136</ProcessorSpeed>
        <ProcessorCount>8</ProcessorCount>
        <ProcessorCores>0</ProcessorCores>
        <PhysicalMemoryMB>15982.59375</PhysicalMemoryMB>
        <ComputerName>...</ComputerName>
        <ComputerModel>N/A</ComputerModel>
        <UnityVersion>2017.2.0</UnityVersion>
        <SupportedLicenseVersion>6.x</SupportedLicenseVersion>
    </SystemInfo>
    <License id="Terms">
        <MachineID Value="..." />
        <MachineBindings>
            <Binding Key="1" Value="..." />
            <Binding Key="2" Value="..." />
        </MachineBindings>
        <UnityVersion Value="5.6.0" />
    </License>
</root>
```

I was thinking that maybe if we could, generate this file, send the request to the proper api endpoint, then write the license file to disk, we would allow free licenses to be used. It's not like the UI did anything that a script can't do. ;)

However, I'm not sure that's something allowed by the Terms of use of the Unity services.

If this is something you'd be interested in, I'll have a look into that.

> But thanks for bringing this up, I will make sure to verfiy and look into this once more. I know Unity is working on a special licensing model for build machines.

Oh! I had no idea Unity was looking at a licensing for build machines. That would be great! :)

**Comment by FejZa** [comment]
Hi @Nemikolh, that sounds interesting. Not sure whether there are any hidden traps or issues with that approach. If you could verify it works, adding it to the extension would make sense. Also make sure it does not violate any terms of use.

**Comment by FejZa** [comment]
Closing this since I have no plans of implementing this myself.
