### ISSUE TITLE
Issue while installing Unity

### ISSUE THREAD

**Issue by Sid911** [Dinomite-Studios/unity-azure-pipelines-tasks#111]
Hi, I am trying to get my setup running on azure pipelines.. I am stuck on this on task where I have to install Unity using 
```
Install-UnitySetupInstance -Installers (Find-UnitySetupInstaller -Version '$(unitygetprojectversion.projectVersion)' -Components Windows,Windows_IL2CPP) -Verbos
```

but there no output option while getting the project version 

![image](https://user-images.githubusercontent.com/27860105/73140822-21d9f300-40a3-11ea-9665-8f25999017fd.png)

I don't know if Environment Variable is being set or not, it would nice if someone could solve this issue😀

**Comment by FejZa** [comment]
Hi @Sid911, that UI does not look familiar to me. Where did you take it? You need to open the pipeline for editing to see the output variable configuration.

**Comment by Sid911** [comment]
@FejZa That's the assistant view when adding code to yml file

**Comment by FejZa** [comment]
Ah I see. I am not using YAML so far. Only the visual designer so I am not able to assist here. But there must be a way to specify output variable names in YAML as well.

**Comment by Sid911** [comment]
@FejZa where can I find the visual designer?

**Comment by FejZa** [comment]
You cannot go back and forth. When creating a new pipeline look for "Use the visual designer" in one of the first steps. Once you created a pipeline using YAML you cannot convert it to visual designer.

**Comment by FejZa** [comment]
![image](https://user-images.githubusercontent.com/9565734/73442019-51635680-4354-11ea-97bc-e6162a3490f5.png)

It's right in the first step when you create a new pipeline

**Comment by Sid911** [comment]
@FejZa Got.. it .. I got it working anyways.. but you might want to look into yml approach and why some of the things are visible and some are not 😄😃

**Comment by FejZa** [comment]
Thank you for the update! I'll definitely take a look at why YAML seems to be different here. Supposedly it should be the same in behaviour and no adjustments needed....
