### ISSUE TITLE
Find-UnitySetupInstaller command not working

### ISSUE THREAD

**Issue by kakins** [Dinomite-Studios/unity-azure-pipelines-tasks#112]
Followed the instructions here: https://dinomite-studios.github.io/unity-azure-pipelines-tasks/hosted-agent.html

![image](https://user-images.githubusercontent.com/14915247/75000599-6ba8c580-5424-11ea-88ec-90b5571455f5.png)

The UnitySetup.PowerShell module seems to have completed successfully.  Not sure what I'm doing wrong.

**Comment by kakins** [comment]
Found the issue.  I copied the powershell command directly from your instructions.  However you screenshot contains some extra parameters (`-Scope CurrentUser -Force`).  Once I added those it worked.

**Comment by FejZa** [comment]
Hi @kakins, thank you or reporting the error in the docs! I will make sure to update them!
