### ISSUE TITLE
What versions can you use? (MS's hosted agents)

### ISSUE THREAD

**Issue by MarshMello0** [Dinomite-Studios/unity-azure-pipelines-tasks#116]
I've been trying to get this to run but it seems not to have any version of unity installed.

> ##[error]Not found Unity Editor Directory: /Applications/Unity/Hub/Editor/2018.4.10f1

I saw #97 you said 

> The hosted agents provided by Microsoft don't have the latest Unity version installed. They usually only have the latest LTS release (2018.4) I think.

Do you know which version of 2018.4, as I've tried 4.20, 4.10 and 4.1. All seem to fail.

The reason I am using this is just to try and build an asset bundle, I don't need to build a Unity project.

**Comment by FejZa** [comment]
Hi,

the hosted agents always contain the editor you get when selecting the "Game Development" module installing Visual Studio. So if you take a look there, we can see that it currently installs 2019.2. They don't specify the patch version so I'd assume it's the latest. That is on Windows.

From your log above I assume you are using the hosted macOS agent. Those don't come with Unity installed unfortunately.
