### ISSUE TITLE
Failing Android build

### ISSUE THREAD

**Issue by JanNemcik** [Dinomite-Studios/unity-azure-pipelines-tasks#117]
Hi,

with version 2.* I'm getting folowing error: The Unity build task finished without results. Check editor logs for details. With version 3.* it's The process 'C:\Program Files\Unity\Hub\Editor\2019.2.9f1\Editor\Unity.exe' failed with exit code 1. The build is running for ca 25 mins. If I run the build directly from the Unity Editor on the server it's working. Any hints?

**Comment by JanNemcik** [comment]
Update: now it's failing on Execution failed for task ':mergeReleaseResources' but the build in the Editor itself is fine

**Comment by FejZa** [comment]
Hi. I published a new update to the extension. v2.7 should help identifying your issue since it's now streaming the build logs to devops while building. Please verify you issue still exists and feel free to repoen this issue, if it does.
