### ISSUE TITLE
Devops Pipeline hangs when building with inline or pipeline script

### ISSUE THREAD

**Issue by Reinhartdelille** [Dinomite-Studios/unity-azure-pipelines-tasks#137]
Hi
First of all, thank you so much for this addon ... really love it.

Noticed today that when you configure the Unity Build Task with Existing Build Script Execute Method, or with an Inline script, the Build task seems to hang on completion.

I added -nographics -quit to the Arguments and then it seems to work fine. (actually the nographics is not required but added that for performance reasons anyway)

Might wanna add that to the docs :)

![image](https://user-images.githubusercontent.com/19047081/83338800-06d4f500-a2c8-11ea-8758-1a24273f9b9a.png)

Kind regards
Reinhart

**Comment by FejZa** [comment]
Hello Reinhart,

this is a valid point thank you! When using a custom script the -quit parameter should be added unless the custom script takes care of exiting the editor.

**Comment by Reinhartdelille** [comment]
Thank you for the response.

Hadn’t given it good thought yet, but it perfectly makes sense. As i use the same buildscript (with menu item) in Unity as in Azure Devops, putting an application Quit in the buildscript might impede my Unity productivity.

So adding it as an argument is the best option.

Thanks again, good work !

**Comment by axtox** [comment]
I wonder, could this `-quit` option help with our issue? #129

**Comment by Reinhartdelille** [comment]
I think this is the reason yes, without knowing what your build script does of course. Generally in an Editor scripts you will not issue Application.Quit, but it's something that's run in Unity and does leaves Unity open.

As a result, when you run it from command line (or in a pipeline task, of powershell script), adding -quit might solve the issue.

Don't really know if the Azure Pipelines task stopped the process after a successful (or unsuccesful build), I tried with V2 and had the same results.

**Comment by axtox** [comment]
I see, but the problem is that when we use the direct script in Pipeline Command Line task, we see the correct behavior - it ends once the build is ready and there's no Unity Editors remaining opened. I will try to add the `-quit' option to Unity Pipeline Task in the Arguments section to see if it helps. 
Let's continue the conversation in #129 issue page.

**Comment by bdovaz** [comment]
@FejZa It should be much better documented that if you don't use the default method for "-executeMethod" that you have to explicitly put the parameter "-quit" in "additionalCmdArgs".

It has made me waste several hours thinking that it was some concrete configuration of the machine that made Unity stay frozen.
