### ISSUE TITLE
Unity running while agent is running halts the agent

### ISSUE THREAD

**Issue by NikolasKilian** [Dinomite-Studios/unity-azure-pipelines-tasks#15]
If you have the Unity Editor open on the same machine the agent is running on, the build task will think it's the one it started, making the task repeat
`Checking whether Unity process is still running...`
`Unity process still running. Will check again in 30 seconds...`
indefinitely until you close the editor.
I would expect the same to happen should you have 2 agents running on one machine, with both closing only once both are finished, although I have not tested this yet.

**Comment by FejZa** [comment]
Fair enough, I didn't think about that. I am going to have a look at this and see if I can filter for the specific Unity process created by the running task.

**Comment by FejZa** [comment]
Fixed in v2.7
