### ISSUE TITLE
UnityTestTask@1 should allow passing additionalCmdArgs to collect code coverage

### ISSUE THREAD

**Issue by bdovaz** [Dinomite-Studios/unity-azure-pipelines-tasks#150]
Please look at this package:

https://docs.unity3d.com/Packages/com.unity.testtools.codecoverage@0.3/manual/UsingCodeCoverage.html

It allows you to collect code coverage and requires you to add more parameters per command line.

**Comment by FejZa** [comment]
This is now released to the marketplace. The extension version containing it is 2.7.3. Thanks again @bdovaz!
