### ISSUE TITLE
We are using Unity Collaborate as our source and we need to manually open unity and get latest code prior to running our DevOps pipeline.  Is there a command line that can get any Unity Collaborate updates so this does not need to be done using the UI manually?

### ISSUE THREAD

**Issue by greenrya** [Dinomite-Studios/unity-azure-pipelines-tasks#154]
We are using Unity Collaborate as our source and we need to manually open unity and get latest code prior to running our DevOps pipeline.  Is there a command line that can get any Unity Collaborate updates so this does not need to be done using the UI manually?

_Originally posted by @greenrya in https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/153#issuecomment-724119616_

**Comment by FejZa** [comment]
Collaborate has been discontinued. In any case these utilities work with whatever version control system Azure DevOps supports and checking out the latest source is handled by Azure DevOps and not these utilities.
