### ISSUE TITLE
-noGraphics always enabled for tests, breaks tests using compute shaders

### ISSUE THREAD

**Issue by fnuecke** [Dinomite-Studios/unity-azure-pipelines-tasks#169]
From [what I can tell](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/blob/main/Tasks/UnityTest/UnityTestV1/unity-test.ts#L83), the `-noGraphics` command line argument is always passed when running tests using the `UnityTest` task.

This leads to tests using compute shaders to fail.

It would be great if there were an exposed parameter for this, similar to `batchMode`.

**Comment by FejZa** [comment]
Thank you @fnuecke for this suggestion. An update for the extension (v2.8.3) has just been released to the marketplace with this feature implemented.

**Comment by fnuecke** [comment]
Thanks!
