### ISSUE TITLE
SteamingAssets is not the same as Unity Editor build

### ISSUE THREAD

**Issue by eusebiu** [Dinomite-Studios/unity-azure-pipelines-tasks#188]
In a VR project (SteamVR with MRTK) with XR pipeline enabled, the StreamingAssets folder does not contain the same files as the one build by Unity Editor - i.e. the OpenVRSettings.asset file is missing in StreamingAssets/SteamVR - this is not in project's StreamingAssets/SteamVR folder but I think it is copied from Assets/XR/Settings by the Editor build.

Task version: 2.*
Unity 2021.1.21

Demo project: https://1drv.ms/u/s!Aq1jgNgVNaunk3bg8TfmGd9jnkcS?e=mhqhqH

**Comment by FejZa** [comment]
Hello and first of all I am sorry for leaving you hanging with this for years literally.
Unfortunately this does not seem to be an issue with the build tasks itself. They simply trigger a build process.
I'd suspect the issue to be within the `BuildWin64.PerformBuild` script and how it handles being executed in batchmode.
