### ISSUE TITLE
Post-job: UnityActivateLicenseTask

### ISSUE THREAD

**Issue by RobertPastisss** [Dinomite-Studios/unity-azure-pipelines-tasks#194]
Hi guys,

I'm using Azure DevOps with a YAML file.

At each build launch I have a problem with Post-job: UnityActivateLicenseTask, in fact there is no deactivation of the license.

I think we need to have "username", "password" and the "serial' on post-unity-activate-license.ts file (like unity-activate-license.ts). 

If we look the docs  (this one https://docs.unity3d.com/Manual/ManagingYourUnityLicense.html) we need those informations. 

In my case if we look the log i have ""C:\Program Files\Unity\Hub\Editor\2022.1.1f1\Editor\Unity.exe" -batchmode -quit -returnlicense ..." 

And we need something like that ""editor-location" -quit -batchmode -returnlicense -username 'name@example.com' -password 'XXXXXXXXXXXXX'"

**Comment by FejZa** [comment]
Fixed in v2.9.0 of the extension package.

**Comment by jambstud** [comment]
looks the behavior still persist.  Any workaround ? 
![image](https://user-images.githubusercontent.com/91638159/227806485-f11cbc49-d20e-469c-9059-0175db4f8a17.png)
