### ISSUE TITLE
Build failure with Unity 2017

### ISSUE THREAD

**Issue by Andrey-Svetlichny** [Dinomite-Studios/unity-azure-pipelines-tasks#21]
Running Unity 2017.2.5f1 got error:
The Unity build task finished without results. Check editor logs for details.
Really problem with AzureDevOps.cs - UnityEditor.Build.Reporting API different for Unity 2017
I didn't found source of AzureDevOps.cs, only file in _work directory.
Is it possible to change template for AzureDevOps.cs?

**Comment by FejZa** [comment]
Hi,

thank you for reporting this. I'll make sure to adjust the script to work for those "older" Unity versions as well later today and publish an update.

**Comment by Andrey-Svetlichny** [comment]
Thank you a lot! 
Kind regards,
Andrei Svetlichnyi

17 января 2019 г. 18:30:03 GMT+01:00, Dino Fejzagic <notifications@github.com> пишет:
