### ISSUE TITLE
Size of the VSIX package

### ISSUE THREAD

**Issue by mh-ka** [Dinomite-Studios/unity-azure-pipelines-tasks#210]
Hi there,

I had issues installing the extension on a Azure DevOps on-premise server. The proposed SQL changes on the maximumpackagesize value did not work for me.

Had a look into the package itself and saw that in every task folder, the complete Typescript folder is present which is quite big. Is this necessary? (see attached screenshots below)

There is [an article](https://levelup.gitconnected.com/reducing-a-visual-studio-extension-vsix-file-size-86ed72fbcf39) on optimizing the package size. Do you think, this is feasible? 

![blub1](https://user-images.githubusercontent.com/52745439/201718762-6de0887f-48bc-432f-99ed-57a7484bf0e2.JPG)
![blub2](https://user-images.githubusercontent.com/52745439/201718764-91390884-e438-44cc-81a7-2ef03031c841.JPG)

Regards,
M

**Comment by FejZa** [comment]
This has been "fixed" in recent released by omitting dev depencendies for release builds. Thank you for reporting and I am sorry for not ever getting an answer. I am now back to maintaining this repository more regularly.

**Comment by mh-ka** [comment]
Thanks for coming back to this issue
