### ISSUE TITLE
Feature Request: Unity activation to support activating a personal license for a specific username / password

### ISSUE THREAD

**Issue by SimonDarksideJ** [Dinomite-Studios/unity-azure-pipelines-tasks#222]
Certain projects rely on Unity services which require the installed version of Unity to be registered with a personal license using just their username/password, this is required to access the services for the organisation when building the project.

**Comment by FejZa** [comment]
Hi @SimonDarksideJ , unfortunately this is not supported as the only way to activate a personal license is to use the Unity Hub UI. This is stated in the official docs found [HERE](https://docs.unity3d.com/Manual/ManagingYourUnityLicense.html).

I will revisit this if it changes in the future.
