### ISSUE TITLE
Simple changes needed to pass Quality Analysis 

### ISSUE THREAD

**Issue by paulio** [Dinomite-Studios/unity-azure-pipelines-tasks#254]
When a Unity project is using standard Microsoft Code Analysis Quality rules, it fails because AzureDevOps.cs fails on 3 rules. 
- Lack of a namespace
- Not using a specific exception handler
- error CA1052: Type 'AzureDevOps' is a static holder type but is neither static nor NotInheritable

The changes needed are simple but without them the class fails the whole build.
A potentially simple solution is to check for the presence of the AzureDevOps.cs and leave it alone if it's already there - potentially a flag option. That would allow for any customizations required by the client.

**Comment by FejZa** [comment]
https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/255
