### ISSUE TITLE
Breaking change in unityEditorsPathMode

### ISSUE THREAD

**Issue by bdovaz** [Dinomite-Studios/unity-azure-pipelines-tasks#263]
For some reason the option to set by environment variable the path to Unity editors has been removed without an issue or PR with proper justification: https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks-lib/commit/ff3396229740d1cffea1783061730daa81fb3107

In our case this is a big problem because for disk space reasons we have configured in the Unity hub to install them in a different disk and for that reason we used that environment variable `UNITYHUB_EDITORS_FOLDER_LOCATION` at agent level (each one with a different value).

Now when removing that option it is assumed that they are going to be installed in the default option for each OS and that does not have to be like that:

https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks-lib/blob/739837ed11ebfab1d394279c583c6468c6c2cc3f/lib/unity-path-tools.ts#L34

![image](https://github.com/user-attachments/assets/083e12af-7865-4329-a423-9d328acadfe3)

There is an API to get the path configured in the hub without assuming anything (example in Windows):

https://docs.unity3d.com/hub/manual/HubCLI.html#setget-install-path

```
"C:\Program Files\Unity Hub\Unity Hub.exe" -- --headless install-path --get
```

cc @FejZa

**Comment by bdovaz** [comment]
@FejZa I have created a PR to get the information this way but I have not been able to check that it works because I don't know how to execute this code manually honestly because I have no experience neither in TypeScript nor in developing tasks....

**Comment by EMI0101** [comment]
While the PR is nice, this doesn't fix the issue of breaking existing options within the same task version.

**Comment by FejZa** [comment]
The issue has been adressed in v2.9.5 by reverting the change. @bdovaz I will still look into your PR and see if we can make the automatic look up the new "default" instead of assuming defaults.

**Comment by FejZa** [comment]
@bdovaz which task are you referring to? I did add it to the task.json

**Comment by EMI0101** [comment]
Unsure what the cause is, but build task on 3.2.3 and test task 1.5.1, still have the error when using environmentVariable.

<img width="1127" alt="image" src="https://github.com/user-attachments/assets/c5e973a1-cca6-419b-890e-175bd5710868">

**Comment by FejZa** [comment]
Oh boy I just realized why. Sorry need to make another update. I updated the shared library package but did not bump the dependency in the task itself.

**Comment by FejZa** [comment]
Ok, let's this time it is fixed for good. Really sorry for the incovenience.

**Comment by EMI0101** [comment]
Can confirm it works! Thank you for your help.

**Comment by bdovaz** [comment]
> Ok, let's this time it is fixed for good. Really sorry for the incovenience.

@FejZa no problem, thanks for your hard work!

**Comment by bdovaz** [comment]
@FejZa even deleting the “_tasks” folder in the agent I still download the task “1.2.2” (having referenced the task with `@1`) when in the repository is the “1.2.3”. Is it my problem alone? If so, is it a matter of waiting or do you know if it can be forced to use that version?

Thanks!

**Comment by bdovaz** [comment]
@FejZa two problems:

1. I now get this error without touching anything in my pipeline using `UnityCMDTask@1` and `unityEditorsPathMode: environmentVariable` with the `UNITYHUB_EDITORS_FOLDER_LOCATION` variable defined at agent level:

```
The “path” argument must be of type string. Received undefined
##[error]The “path” argument must be of type string. Received undefined
```

2. I mark the task `UnityCMDTask@1` as deprecated because you marked it here:

https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/commit/dceebce7353cea112b3e7dfe7c00aede9a3aba6b#diff-9f87d2aaeeed211e1ff906aa5f753bb543ff4a8427b572a867766c9142dfffa7R5

Why? There is no `@2` or anything to migrate to.

**Comment by FejZa** [comment]
Unity CMD has been deprecated because Unity Build can be used in the same way and it is redundant.
That path argument error is as old as time. While most users don't get it it appears every now and then for many as well.  Let me check other cases where it appeared and how it was fixed potentially.

**Comment by bdovaz** [comment]
> Unity CMD has been deprecated because Unity Build can be used in the same way and it is redundant. That path argument error is as old as time. While most users don't get it it appears every now and then for many as well. Let me check other cases where it appeared and how it was fixed potentially.

The path error is the first time it has happened to me in years and I release several builds a day. That's why I'm worried that it's something caused by this version.

About the Unity CMD task I have created an issue because it has its own relevance: https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/264
