### ISSUE TITLE
Another breaking change with logsOutputPath variable in UnityBuildTask task

### ISSUE THREAD

**Issue by bdovaz** [Dinomite-Studios/unity-azure-pipelines-tasks#265]
In this commit you have removed it without an issue or PR: https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/commit/dceebce7353cea112b3e7dfe7c00aede9a3aba6b#diff-452735be9ea01bc188904a83af7b9f2ddca5949e04c4ab5a6ecad067bb06f7da

Putting this comment: “Remove logs output variable since temporary anyways”.

And it is not true, in our case we always use it to generate an artifact with the log to avoid having to access the agent that not everyone has permissions for it and even if you have them, it is not easy: ssh, etc...

There are other cases in which, for example, if UPM errors occur, they do not even appear in the task output and the log file https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/214 must be consulted.

**Comment by FejZa** [comment]
I appreciate your input a lot and I am going to watch out better with these kind of changes in the future. I now understand better how diverse the usage of these extensions actually is for everyone.

**Comment by bdovaz** [comment]
Maybe you didn't read in my first message but there are cases like this that are not covered by the log that comes out of the console:

> There are other cases in which, for example, if UPM errors occur, they do not even appear in the task output and the log file #214 must be consulted.

Besides, having access to the whole file (which is sometimes huge) allows you to do regex searches more easily.

**Comment by FejZa** [comment]
I see. Let's use this opportunity then to not only bring back how it was but improve on it potentially.
