### ISSUE TITLE
Consensus on changes that are also breaking changes before making them

### ISSUE THREAD

**Issue by bdovaz** [Dinomite-Studios/unity-azure-pipelines-tasks#266]
Seeing the precedents: https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/263 https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/264 https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/265

I think you should check with the community before making changes of this type because you seriously affect certain use cases (in some cases more advanced) that you do not take into account.

And improve traceability that every time you make a change there is an issue and a PR because many changes you have made @FejZa “have slipped” in a release without the relevance it should have to be breaking changes not contrasted with the community.

@FejZa if you find yourself overwhelmed I offer to be a contributor to the repository among other things. I've been one for a long time with @xoofx at https://github.com/xoofx/UnityNuGet

**Comment by FejZa** [comment]
Hey @bdovaz, happy to make you a contributor to the project. Would love to get your feedback and review on upcoming PRs.

**Comment by bdovaz** [comment]
Thanks! Let's see if this way we can get more consensus by having another pair of eyes.
