### ISSUE TITLE
games.dinomite.azurepipelines does not compile in Unity 2018

### ISSUE THREAD

**Issue by JeroenTekle** [Dinomite-Studios/unity-azure-pipelines-tasks#287]
# Unity Tools for Azure DevOps - Bug Report

## Describe the bug

Our pipeline stopped working resulting in Unity returning -1 status for all 2018 projects. Upon further investigation it seems that `AzurePipelinesBuildTemplate` uses the [`PlayerSettings.Android.useCustomKeystore`](https://github.com/Dinomite-Studios/games.dinomite.azurepipelines/blob/main/Editor/AzurePipelinesBuildTemplate.cs#L161) property which does not exist in unity 2018.

## To Reproduce

Try to build a 2018 unity project.

## Expected behavior

A successful build should be made.

## Actual behavior

-1 status error due to not being able to compile scripts `AzurePipelinesBuildTemplate`

### Agent Type

- [ ] Hosted
- [X] Self Hosted

### Build Targets

- [X] Windows
- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Other (please specifiy)

### Unity Version

2018.4.36

**Comment by FejZa** [comment]
Thank you @JeroenTekle, I will fix this by end of tomorrow.

**Comment by FejZa** [comment]
Hi @JeroenTekle, this has been fixed. Please do report back if you still have issues. Do make sure to do a clean build so avoid any caching issues with the package.

**Comment by JeroenTekle** [comment]
Hi @FejZa, it works again. Thank you very much for the quick fix, and of course this awesome tool!
