### ISSUE TITLE
IOS Build failed: unity-get-project-version.js does not exists and changing file format to .js has Unexpected token error

### ISSUE THREAD

**Issue by James-Lho** [Dinomite-Studios/unity-azure-pipelines-tasks#49]
[5.txt](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/files/2892424/5.txt)
[error]Exit code 1 returned from process: file name '/Users/james/Documents/vsts-agent-osx-x64-2.146.0/externals/node/bin/node', arguments '"/Users/james/Documents/vsts-agent-osx-x64-2.146.0/_work/_tasks/UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba/1.0.0/unity-get-project-version.js"'.

First error was File not found "unity-get-project-version.js", so I changed file extension from .ts to .js. Next error is "Unexpected token error" Help!

**Comment by FejZa** [comment]
Hi,

you can't just rename the typescript file to js. This sounds to me like you don't have node installed on your agent. Since it is your own agent as far as I can see, you need to install in on that mac.

**Comment by FejZa** [comment]
Closed, dupliate #54
