### ISSUE TITLE
Cannot build an iOS/tvOS project on a Windows PC.

### ISSUE THREAD

**Issue by Lyssun** [Dinomite-Studios/unity-azure-pipelines-tasks#50]
Why we can't build an iOS project on a Windows ?

We can do that Unity normally.

I wanted to use my own agent to build it and another to build the xcode project

**Comment by FejZa** [comment]
Hi there,

to be honest I never checked whether that works and did not consider your scenario. Always build iOS stuff on a mac usually. I'll check whether I can build on Windows for iOS real quick and if everything works, I'll remove that restriction. Thank you for the input!

**Comment by FejZa** [comment]
Hey, I just added support for your scenario and updated the Unity Build task to 2.3.0 and updtad the extension in the marketplace. Make sure to get the update and you are using the Unity Build Task V2.
