### ISSUE TITLE
Not found Unity Editor Directory

### ISSUE THREAD

**Issue by elevir** [Dinomite-Studios/unity-azure-pipelines-tasks#53]
Hello!

I have already seen the issue #9, but I have some different behavior. It can't find directory, but the path is right and I can paste it into explorer and explorer will open the folder with editor. I need help :)

![image](https://user-images.githubusercontent.com/8929511/53560893-78bb0d80-3b5e-11e9-9ba8-3d2770e9defb.png)

Thanks!

**Comment by elevir** [comment]
I found the problem. Need to set agent pool explicitly in "Agent job" settings.

![image](https://user-images.githubusercontent.com/8929511/53562181-c84f0880-3b61-11e9-9934-69f1f8675bcd.png)

**Comment by FejZa** [comment]
Glad you solve it! Have fun building.

**Comment by elevir** [comment]
@FejZa thanks!
