### ISSUE TITLE
No docs for setting up Hosted agents

### ISSUE THREAD

**Issue by AArnott** [Dinomite-Studios/unity-azure-pipelines-tasks#55]
I'd like to build a Unity project on the Hosted Windows agents, but the "PC & Mac Standalone" link in the README is broken.

**Comment by FejZa** [comment]
Please check the comment I made in #54 for an example how to build standalone on hosted. Sorry for the inconvenience. I'll fix and update the docs as soon as I get to it.

**Comment by FejZa** [comment]
Updated docs with hosted agents Setup and example pipeline
