### ISSUE TITLE
Better way to wait for build and check exit code

### ISSUE THREAD

**Issue by AArnott** [Dinomite-Studios/unity-azure-pipelines-tasks#56]
From here:

https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/blob/4a64eda5de819563cb17d3a4da7e1cfdc6a30d2d/Tasks/UnityBuild/UnityBuildV2/unity-build.ts#L83-L94

I suggest replacing it with a far simpler way:

> start "Unity build" /wait "C:\Program Files\Unity\Editor\Unity.exe" -batchmode -buildTarget standalone -projectPath .\src\UnitProject -logfile editor.log -quit

The cmd.exe command `start /wait` will not exit until the process you started exits, and it propagates the exit code of that process back to the caller, allowing the Pipeline to fail with an error. Also, the `-quit` switch ensures that `unity.exe` exits when the build is done.

**Comment by FejZa** [comment]
Thank you. This is pretty interesting, but I am pretty sure that this will not work when using the -executeMethod flag. I've found Unity behaves differently in that case and the command will return before the build / method has finished. I am using this flag since I've found that it's the only way to support all Unity platforms for building. Since there is not a proper value for the -buildTarget flag for all platforms. I'll make sure to reinvestigate on this. This piece of code is a big code smell for me anyway and I'd love to get rid rid of it.

**Comment by AArnott** [comment]
Well, if `-executeMethod` spawns yet another process and exits the first one, then ya I imagine `start /wait` will exit too early. But it still exits later than your current code, and you'll at least get the exit code of that first process which is more than you're getting now. If you combine the `start /wait` approach with watching for an output folder, perhaps that gets the best of both worlds?

**Comment by milsoft** [comment]
@AArnott @FejZa consider wrapping the execution in a powershell job. Look at the documentation for Start-Job Get-Job and Wait-Job. You can also get status of things this way, and there are ways to dig deep to get child processes spawned by the jobs.

**Comment by FejZa** [comment]
@AArnott thanks again for all your input. I just wanted to ask, whether you are planning to do any PRs with those changes yourself so I can manage what to tackle next myself.

**Comment by AArnott** [comment]
I'm not, no. I can't effectively test any of it since as it turns out Cloud license activations don't work at all for free subscription levels of unity.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FejZa** [comment]
Ah I see. Sorry, I was assuming you have a plus / pro seat. Yes, unfortunately it's required currently. But Unity has announced some changes here and special licensing options for build machines actually. Should be comming around the 2019.2 release timeframe.

**Comment by FejZa** [comment]
Fixed in v2.7
