### ISSUE TITLE
Unity Build task's "Logfile name" parameter assumes relative paths

### ISSUE THREAD

**Issue by AArnott** [Dinomite-Studios/unity-azure-pipelines-tasks#57]
Azure Pipelines encourages building artifacts into the `$(Build.ArtifactStagingDirectory)` folder, and from there it is convenient to publish those artifacts.
I like to put my logs under `$(Build.ArtifactStagingDirectory)\build_logs` and publish the artifact there so they can be inspected later. The Unity Build task lets me specify the log file, but it concatenates whatever I put there with the path to the source directory, so it looks like this: `c:\a\1\s\c:\a\1\a\build_logs\editor.log` Notice that `c:\` appears twice.

The Unity Build task should instead use a proper path joining function instead of string concatenation so that if the log I specify is a fully-qualified path, it disregards the path that it would prepend to a relative path.

**Comment by milsoft** [comment]
In the mean time, I believe you can use relative pathing (like ../../) and IIRC there is a built-in variable to represent the system drive (could be wrong)

**Comment by AArnott** [comment]
> IIRC there is a built-in variable to represent the system drive (could be wrong)

I was using a built-in variable to get the root path, but the task added it to the end of another path, so the end result was an invalid path.

Between this bug, and the lack of `-quit` or printed logs from the tasks, and the fact that at least one of the tasks "succeed" when it should have reported failure, I've actually removed all use of these tasks and switched to cmd scripts, which seems like it should work except that I still can't figure out how to license Unity (with or without your Task). My problem may be that I don't have a complete serial number (the one I get comes from Unity->About Unity, which ends with 4 X's, and I think that's hiding a real number.

In [this build](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=1110) you see I try activating with my own script and with the Task, and the task reports success but it had actually failed. My script fails too, and reports failure.

**Comment by FejZa** [comment]
Thank you again. The license activation task definitely works or everything is setup correctly. I understand I need to improve the debugging and documentation here. Please note that you need the serial key which you can find under unity3d.com when you login to your account and enter seat management. Under "my seats" your serial is displayed. Please note as well that a serial key can only be activated on 2 machines at the same time. So if you are using it already in two machines, the activate task will fail. The activation task will release the serial from the used agent post build.

**Comment by FejZa** [comment]
Also I would love to use artifactstaging a and other predefined paths but I've found that the tasks would give me permission / access failures in some cases where the Unity.exe would not have permission to write to those paths. I'll double check on this as well once I get back from vacation.

**Comment by AArnott** [comment]
> but I've found that the tasks would give me permission / access failures in some cases where the Unity.exe would not have permission to write to those paths

I've learned that unity.exe will *not* create directories first before trying to write a log to a given path. So in my scripts I create the directory first. For example, here is my activation script:

```cmd
md "$(Build.ArtifactStagingDirectory)\build_logs
start "Unity Activate License" /wait "C:\Program Files\Unity\Hub\Editor\$(unitygetprojectversion.projectVersion)\Editor\Unity.exe" -batchmode -quit -nographics -logfile "$(Build.ArtifactStagingDirectory)\build_logs\unity_license_activation.log" -username "$(UnityUsername)" -password "$(UnityPassword)" -serial $(UnitySerialNumber)
SET unity_error=%ERRORLEVEL%

ECHO Log file follows:
type  "$(Build.ArtifactStagingDirectory)\build_logs\unity_license_activation.log"
exit /b %unity_error%
```

**Comment by AArnott** [comment]
> Under "my seats" your serial is displayed. 

Not for me. I've checked all the screens around My Seats that I can find, and none of them show a seriali number:

![image](https://user-images.githubusercontent.com/3548/54926436-91a0af80-4ecd-11e9-95ec-054e5af948c9.png)

**Comment by FejZa** [comment]
This issue is resolved in V3 of the build Task I hope to release as soon as I finish work on #56.
You will be able to achieve what you describe above by entering
`$(Build.ArtifactStagingDirectory)\build_logs\EditorLog.log` into the additional args field.
