### ISSUE TITLE
Cannot specify `-logfile` for license activation task

### ISSUE THREAD

**Issue by AArnott** [Dinomite-Studios/unity-azure-pipelines-tasks#58]
The activate Unity license task should have a field where I can specify the log file. Otherwise failures are impossible to investigate.

**Comment by FejZa** [comment]
Please see my comment on #59

**Comment by FejZa** [comment]
The activation task has an output variable to get the activation log file, so I'm going to close this one.

**Comment by AArnott** [comment]
It's up to you. But I want all logs in the directory I specify so I can trivially publish them as part of the build. Getting a variable of where it went without my direction means I have to add another step to move it where I want it to be.

**Comment by FejZa** [comment]
Yes, I am still having a look into that as part of the other issue.
