### ISSUE TITLE
Unity Activate License task reports success after failure

### ISSUE THREAD

**Issue by AArnott** [Dinomite-Studios/unity-azure-pipelines-tasks#59]
See [this build](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=1110&_a=summary) as an example of where license activation fails, but the Task reports success anyway. You can see it fails on the next step where I do it with my own script which correctly detects the failure and even re-prints the log for easy review.

**Comment by FejZa** [comment]
Thank you. Actually the activate task provides an output variable pointing to the logfile. I'll make sure to add a file path input to stay consistent with the build task.

**Comment by gilbdev** [comment]
Can you make the licence task fail when unity application return code is not 0 ?
just asking for confirmation, as it's not clear in your last answer.

**Comment by FejZa** [comment]
Fixed in v2.7
