### ISSUE TITLE
Tasks should use `-nographics` parameter to unity.exe

### ISSUE THREAD

**Issue by AArnott** [Dinomite-Studios/unity-azure-pipelines-tasks#60]
[Unity is failing to build on my Azure Pipelines](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=1103&view=logs&jobId=275f1d19-1bd8-5591-b06b-07d489ea915a&taskId=825dd11c-f94a-5d2f-444d-fb3b5d4c1fb0&lineStart=10&lineEnd=11&colStart=1&colEnd=1) using a Hosted agent with this error:

> [0324/154455:ERROR:gpu_info_collector_win.cc(103)] Can't retrieve a valid WinSAT assessment.

It turns out this is because `-nographics` is missing from the cmdline. Adding it avoids this error, but I can only do this by replacing the task with my own script -- the task offers no way to add switches to the command line.

**Comment by FejZa** [comment]
Thank you for reporting. I'll check whether it makes sense to have this flag always set or add it to the advanced options foldout.

**Comment by FejZa** [comment]
Implemented and merged to develop branch. Will be avaialble in the next release. Since using -nographics implies you cannot bake GI on build and use Enlighten it was added as an optional Parameter in the advanced Group of the build Task
