### ISSUE TITLE
Entering a scene path with backslashes causes errors in AzureDevOps.cs

### ISSUE THREAD

**Issue by adrianimajion** [Dinomite-Studios/unity-azure-pipelines-tasks#64]
Including backslashes in the scene path (ie \Assets\Scenes\Scene.unity) will cause the code generator for AzureDevOps.cs to mangle the paths since the backslashes are not escaped properly. This causes build failures.

**Comment by FejZa** [comment]
Hi @adrianimajion, thank you for reporting. I'll have a look into this.

**Comment by adrianimajion** [comment]
@FejZa , I adjusted the slashes in my path and I'm no longer getting the error about an unexpected \ but I am still getting an error in AzureDevOps.cs because of an extra ;. The activation works fine, the build processes fine until it hits this at line 16:

`            private static string[] includedScenes = new string[]
            {
                Assets/Content/Scenes/scene.unity
            };;
`
The extra semicolon is causing the build to fail. I thought the string in the initializer would need to be quoted as well, but it's not causing an intellisense error for me, at least.

**Comment by FejZa** [comment]
Yes, I just noticed this as well. That one really slipped through my fingers. I fixed all the issues with the Code here and am currently Performing test builds. Bare with me, I'll update you soon.

**Comment by adrianimajion** [comment]
Thanks for the fix and for creating this tooling in the first place - looks like we're both working with the HoloLens, hopefully I can contribute something useful to this repo in the future! I'd like to write up some documentation on using this with Azure Dev Pipelines to accompany the resources you've posted already - I'd like to post a blog article or something, but I'd be happy to fold the new info into the documentation as well. I worked out a number of quirks with the process certifying UWP in the ADP build etc.

**Comment by FejZa** [comment]
Thank you for bringing it to my attention. Happy to say the fix is live on the marketplace now and I have release v2.4.0 of the extension. It also adds an option to specify the -nographics flag on build. Also happy for any contributions :)
