### ISSUE TITLE
Building UnityBuildV1 task as documented causes shell errors

### ISSUE THREAD

**Issue by adrianimajion** [Dinomite-Studios/unity-azure-pipelines-tasks#66]
Following the documentation at : https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/blob/master/Tasks/UnityBuild/UnityBuildV1/README.md

Fails on 3 errors in Powershell:

`Tasks/UnityBuild/UnityBuildV1/unity-build.ts:2:21 - error TS2307: Cannot find module 'azure-pipelines-task-lib/task'.

import tl = require('azure-pipelines-task-lib/task');

Tasks/UnityBuild/UnityBuildV1/unity-build.ts:3:21 - error TS2307: Cannot find module 'fs-extra'.

import fs = require('fs-extra');

Tasks/UnityBuild/UnityBuildV1/unity-process-monitor.ts:1:30 - error TS2307: Cannot find module 'find-process'.

import findProcess = require('find-process');

Found 3 errors.`

This may primarily be a problem in my understanding of  building Typescript. Just trying to race you to fix that issue in unity-build-script-helper.ts ;)  , cheers

**Comment by FejZa** [comment]
Thank you. Actually that doc is missing an essential piece of Information :). You have to do npm install first to get the required node packages installed for building.

So navigate the console into the task's folder, e.g. UnityBuildV2 and then execute `npm install`, after that you will be able to compile the TypeScript. Every Task has an own `packages.json` which lists the required external packages.

Plesae consider using UnityBuildV2, Version 1 ist just there for "legacy support".
