### ISSUE TITLE
Enhancement: Support custom PlayerSettings or a user-provided build script

### ISSUE THREAD

**Issue by adrianimajion** [Dinomite-Studios/unity-azure-pipelines-tasks#70]
I'm running a pipeline which requires PlayerSettings.virtualRealitySupported and PlayerSettings.VirtualRealitySDKs to be modified for certain build targets. This is supported by Unity build scripts using the PlayerSettings class. 

Using that functionality via the command line is laborious, but likewise if you need that functionality this task can't be used. It would be fantastic to be able to upload a .cs source file or just copy and paste PlayerSettings parameters to be inserted during build.

**Comment by FejZa** [comment]
Thank you @adrianimajion. Sorry I Kind of missed this issue and just noticed it again. I'll make sure to look into this it makes perfect sense to be able to build XR projects.

**Comment by StephenHodgson** [comment]
@adrianimajion I think that's just something you'll need to build into your build command line executable.

Why not [take a look at the XRTK](https://github.com/XRTK/XRTK-Core/blob/c3e3c8fc9ae3549a1a501d07bff5dc3d857e2c94/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs#L156) and see how we handle it. We support many VR/AR platforms and build correctly.

**Comment by adrianimajion** [comment]
@StephenHodgson, thanks for your input. I agree there is a scope question inherent here that is up to the creator to answer. Personally, in my view this task could abstract any personal modification of the command line executable.  Because the PlayerSettings class is well documented and many Unity automated build contexts require adjusting it, I think it's reasonable to add some kind of support for customizing its parameters from the task's GUI in Pipelines. Unity Cloud Build provides support for adjusting PlayerSettings parameters from the GUI, if I'm not mistaken. Right now I am using an approach similar to your example, but that precludes use of the task. My problem is sorted out, but I figured I'd suggest this feature as a potential change to the task for other users.

**Comment by FejZa** [comment]
Thank you guys. I am Looking into adding "pro features" to the task for v3 of the build task. Initially I wanted to Keep it simple.

**Comment by FejZa** [comment]
This is resolved in v2.7 of the extensions. You can now specify your own build scripts or use the new `Unity CMD` task for full control.
