### ISSUE TITLE
How to pass in custom arguments for msbuild?

### ISSUE THREAD

**Issue by jpt007** [Dinomite-Studios/unity-azure-pipelines-tasks#81]
I'm trying to get a build result up to the VS App Store. Looks like a UWP build needs to be packaged and signed if it's to be deployed to the App Store. How would I pass in msbuildargs to support bundling appx? I could be completely missing something and I noticed a reference in the build task to custom command line args. Any help is much appreciated.

https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps

**Comment by FejZa** [comment]
Hi @jpt007,

you can package UWP easily using this extension. The Unity Build Task will Output a VS solution and then you're going to use the out of the box Visual Studio Build Task to build a UWP package, this Task has everything you need.

Here's what a UWP Pipeline on a hosted agent Looks like to build a Unity Project and get a UWP appx package Ready for store upload:

![UWP](https://i.ibb.co/dkJ04KG/uwp-pipeline.jpg)

Task 1 through 6 basically install the right Unity editor on the agent, activate a License and build the Unity Project for UWP. Then build Output is copied to the binaries directory. From here, It's just like Building any UWP project.

Let me know, if you Need any more help.

**Comment by jpt007** [comment]
Thanks @FejZa . This is helpful. I'll give it a shot.

**Comment by jpt007** [comment]
@FejZa - This helped me get further along and root issue. Looks like the sln and supporting files that's produced from the Unity Build has issues with Visual Studio. I tried opening up the sln in VS 2017. All projects loaded fine, but the build failed.

```
... 
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe /out:"C:\Projects\jttest\build\obj\il2cppOutputProject\x64\Debug\linkresult_F24E4D76CB2DBCF96D4D9EC1CA21C63A\GameAssembly.dll" /DEBUG:FASTLINK /INCREMENTAL:NO /LARGEADDRESSAWARE /NXCOMPAT /DYNAMICBASE /NOLOGO /TLBID:1 /HIGHENTROPYVA /DLL /NODEFAULTLIB:uuid.lib "Shcore.lib" "WindowsApp.lib" "Crypt32.lib" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64\store" /APPCONTAINER /SUBSYSTEM:WINDOWS /NODEFAULTLIB:ole32.lib /NODEFAULTLIB:kernel32.lib /NODEFAULTLIB:msvcrt.lib @"C:\Users\jpt00\AppData\Local\Temp\tmp85CF.tmp"
1>
1>Creating library C:\Projects\jttest\build\obj\il2cppOutputProject\x64\Debug\linkresult_F24E4D76CB2DBCF96D4D9EC1CA21C63A\GameAssembly.lib and object C:\Projects\jttest\build\obj\il2cppOutputProject\x64\Debug\linkresult_F24E4D76CB2DBCF96D4D9EC1CA21C63A\GameAssembly.exp
1>7580118BC825767A9A325541CAD370B0.obj : error LNK2019: unresolved external symbol "public: static struct Il2CppString * __cdecl il2cpp::icalls::mscorlib::System::IO::MonoIO::GetCurrentDirectory(int *)" (?GetCurrentDirectory@MonoIO@IO@System@mscorlib@icalls@il2cpp@@SAPEAUIl2CppString@@PEAH@Z) referenced in function MonoIO_GetCurrentDirectory_m58052285E84A0379331FF2FE78A663C9F5C64C21
1>C:\Projects\jttest\build\obj\il2cppOutputProject\x64\Debug\linkresult_F24E4D76CB2DBCF96D4D9EC1CA21C63A\GameAssembly.dll : fatal error LNK1120: 1 unresolved externals
1>
1>   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
1> 
```

**Comment by jpt007** [comment]
@FejZa - I started with a different Unity project and the UWP build was successful. I'm going to close this one. Thanks again for your input.
