### ISSUE TITLE
build fail due to task always checking default outputpath

### ISSUE THREAD

**Issue by gilbdev** [Dinomite-Studios/unity-azure-pipelines-tasks#86]
`setResultFailed('The Unity build task finished without results. Check editor logs for details.');`

in unity-build.ts, it's always the default output path for the platform that is checked to be empty or not.

This is problematic when using a custom build method that output the version in a different folder.

i would like to be able to override the output path (getBuildOutputDirectory)  that is checked as a parameter in the task.

**Comment by FejZa** [comment]
Hi @gilbdev,

thank you. This is fixed with the next version of the build task which I am planning to release soon. V3 generally aims at more advanced use cases and doesn't have as many restrictions as before in how you can use it.

**Comment by tamademicheli** [comment]
Hallo when will this enhancement be released ? is there a workaround ? Thanks

**Comment by FejZa** [comment]
Hi @tamademicheli, I have not date for you unfortunately but I am aiming for a release this month. Just kind of overloaded with work currently so not getting to work a lot on this task. I'll keep you updated.

**Comment by tamademicheli** [comment]
Great Dino! Thanks a lot!

**Comment by FejZa** [comment]
This is resolved in v2.7 of the extension that just got released. Sorry everyone for the deeeeeeeeeeeeelay.
