### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by dmdnkv** [Dinomite-Studios/unity-azure-pipelines-tasks#89]
There is only one task in the pipeline that is Unity build task and I do run it on Self-hosted agent.

I did try several build targets as well as different  unity editor locations but the task is always fails with the following message:

![image](https://user-images.githubusercontent.com/2073188/61023578-311d7b80-a3b3-11e9-88c3-5e6b0ec6d454.png)

>##[section]Starting: Unity Build Android
>
>Task         : Unity Build
>Description  : Build a Unity project and get the exported output files.
>Version      : 1.4.2
>Author       : Dinomite Studios
>Help         : Builds a Unity project to supported build target platforms. [More Information](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks)
>
>##[error]The system cannot find the file specified
>##[section]Finishing: Unity Build Android

What could be the source of this problem?

**Comment by FejZa** [comment]
Hi @dmdnkv, I see you are using V1 of the Unity Build task. Could you try and build with V2? I am not supporting V1 anymoer and it will not get any updates.

When you are editing the pipeline at the top of the Build Task Configuration UI there is a dropdown to select a version.

**Comment by dmdnkv** [comment]
@FejZa I did try both. V2 fails with the same error:
```##[section]Starting: Unity Build Android
==============================================================================
Task         : Unity Build
Description  : Build a Unity project and get the exported output files.
Version      : 2.4.5
Author       : Dinomite Studios
Help         : Builds a Unity project to supported build target platforms. [More Information](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks)
==============================================================================
##[error]The system cannot find the file specified
##[section]Finishing: Unity Build Android

**Comment by FejZa** [comment]
@dmdnkv still looking into this. It's some Android specific issue. Are you on a hosted agent?

**Comment by dmdnkv** [comment]
@FejZa I don't know, but will try to build for other platforms to figure it out. Yes, I do use hosted agent that is run on my local machine.

**Comment by FejZa** [comment]
Closing this. Feel free to reopen the issue if the issues is still happening with the just now published update.
