### ISSUE TITLE
Unity activate license fails

### ISSUE THREAD

**Issue by yvz-dmr** [Dinomite-Studios/unity-azure-pipelines-tasks#93]
Unity activate license fails with this error.

##[error]Error: Not found Unity Editor Directory: C:\Program Files\Unity\Hub\Editor\2019.1.8f1
m_EditorVersionWithRevision\Editor

I have tried all available options in Unity Editor Location but all fails with this error message.

**Comment by FejZa** [comment]
Hey, currently a known issue that I thought was fixed in the last update. I'll take another look at it. Thanks for your patience.

**Comment by joemorin73** [comment]
I've come across the same issue.  Is there anything I can provide?

**Comment by FejZa** [comment]
Hi @yvz-dmr @joemorin73 , I just released v2.5.2 of the extensions to the marketplace. Could you please make sure you updated to that version and run your pipeline again? Please make sure that the `debug` system variable is set to `true`, so we get better output.

If you have the latest versions, you should be seeing these versions used:
Unity Get Project Version: 1.0.4
Unity Activate License: 1.0.4

Thanks for the help!

**Comment by joemorin73** [comment]
Queuing a build now.

**Comment by joemorin73** [comment]
It seems it works now.  No error.  (Well, WinSat error, but I don't believe it's related.)

I've attached the log, in case it helps.
[log_8_4174.zip](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/files/3498405/log_8_4174.zip)

**Comment by FejZa** [comment]
Thank you @joemorin73, glad the issue was resolved. I've seen the WinSat error message as well quite often but it seems it does not affect the tasks.

**Comment by FejZa** [comment]
Closing this, resolved in v1.0.4
