### ISSUE TITLE
usage of Variables on Build Task Arguments

### ISSUE THREAD

**Issue by zu76** [Dinomite-Studios/unity-azure-pipelines-tasks#96]
I'd like to be able to set variables as parameters of the arguments of the build.
I am using Unity Build v3 Preview, and setting a Build Script Method which accept parameters.

In my case I need to define bundleVersions and bundleVersionCode of the build using variables such as $(BuildID).

If I tried, the result was the following (where the variable was passed as text and not replaced with the actual value):
[command]"C:\Program Files\Unity\Hub\Editor\2018.3.8f1\Editor\Unity.exe" -batchmode -buildTarget Android -bundleVersion $(BoundleVersion) -bundleVersionCode $(BuildID) -executeMethod BuildScript.BuildAndroid

Is there a way to perform this?
Thank you
Alberto
P.s. Thank you so much for your work, very useful and appreciated!!

**Comment by FejZa** [comment]
Hi @zu76, now this is interesting and I can see how this is useful! Haven't actually tried that myself yet, so please give me a bit of time to check how this can work.

**Comment by zu76** [comment]
Hi @FejZa , I double-checked and in fact usage of variables is already possibile.
I was using the variable name in wrong way.
I was able to pass variable on the arguments properties (in the format: `$(Build.BuildID)`   )  as well as within the c# build script I build using
`System.Environment.GetEnvironmentVariable("BUILD_BUILDID")`

So I would say it is already working fine.
I am reporting here also the build script I am using now, which I believe satisfy most of my needs in terms of build.
My key point was to be able to have the BundleVersionCode autogenerated as well as have the ability to generate different build per every envirnment (dev, qa, production)

----

`
using UnityEditor;

public class BuildScript
{


    public static void BuildAndroid()
    {

        // Default Arguments

        string projectPath = string.Empty;
        bool buildAppBundle = false;
        string buildType = "prod";

        string bundleVersion = PlayerSettings.bundleVersion;
        string productName = PlayerSettings.productName;
        string applicationIdentifier = PlayerSettings.applicationIdentifier;

        // Initialize Variables from Environment
        string buildPath = System.Environment.GetEnvironmentVariable("BUILD_STAGINGDIRECTORY");
        int bundleVersionCode = System.Convert.ToInt32(System.Environment.GetEnvironmentVariable("BUILD_BUILDID"));





        // Read Arguments
        string[] args = System.Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length; i++)
        {
            switch (args[i])
            {
                case "-bundleVersionCode":
                    bundleVersionCode = System.Convert.ToInt16(args[i + 1]);
                    break;
                case "-applicationIdentifier":
                    applicationIdentifier = args[i + 1];
                    break;
                case "-productName":
                    productName = args[i + 1];
                    break;
                case "-bundleVersion":
                    bundleVersion = args[i + 1];
                    break;
                case "-buildAppBundle":
                    buildAppBundle = System.Convert.ToBoolean(args[i + 1]);
                    break;
                case "-buildType":
                    buildType = args[i + 1];
                    break;
                case "-projectPath":
                    projectPath = args[i + 1];
                    break;
            }
        }

        switch (buildType)
        {
            case "dev":
                applicationIdentifier = applicationIdentifier + "dev";
                productName = productName + " Dev";
                break;
            case "qa":
                applicationIdentifier = applicationIdentifier + "qa";
                productName = productName + " QA";
                break;
            case "prod":
                // Do nothing
                break;


        }




        // Set the build of an Android App Bundle package
        EditorUserBuildSettings.buildAppBundle = buildAppBundle;

        // Build Settings
        PlayerSettings.productName = productName;


        PlayerSettings.applicationIdentifier = applicationIdentifier;
        PlayerSettings.bundleVersion = bundleVersion;
        PlayerSettings.Android.bundleVersionCode = bundleVersionCode;


        // Signing settings
        PlayerSettings.Android.keystoreName = projectPath + "\\my.keystore";
        PlayerSettings.Android.keystorePass = "mypass";
        PlayerSettings.Android.keyaliasName = "my alias name";
        PlayerSettings.Android.keyaliasPass = "mypass";



        // Builder options
        BuildPlayerOptions buildPlayerOptions = new BuildPlayerOptions();
        if (buildAppBundle)
            buildPlayerOptions.locationPathName = buildPath + "\\" + applicationIdentifier + ".aab";
        else
            buildPlayerOptions.locationPathName = buildPath + "\\" + applicationIdentifier + ".apk";
        buildPlayerOptions.scenes = new[] { "Assets/Scenes/myscene1.unity", "Assets/Scenes/myscene2.unity" };
        buildPlayerOptions.target = BuildTarget.Android;
        buildPlayerOptions.options = BuildOptions.None;// | BuildOptions.ShowBuiltPlayer;
        BuildPipeline.BuildPlayer(buildPlayerOptions);
    }
}
`

**Comment by FejZa** [comment]
Glad it works! I was thinking about it and also came to the conclusion it should already work. Thank you for the insight. Are you building on a hosted agent or did you setup your own one? Because I have reports that Android on hosted agents is causing issues.
