### ISSUE TITLE
Option to log to console.

### ISSUE THREAD

**Issue by joemorin73** [Dinomite-Studios/unity-azure-pipelines-tasks#98]
Just curious, is there a reason you are not logging to console?  "-logfile -"
I would think the benefit to review in the pipeline would be preferred.

**Comment by ikriz** [comment]
This would make evaluating why a build failed much easier indeed

**Comment by ikriz** [comment]
Resolved for me :)

**Comment by FejZa** [comment]
Solved in v2.7. The process logs will now stream to the Unity console and can later be retrieved via output variables.
