### ISSUE TITLE
Unable to change file names

### ISSUE THREAD

**Issue by tjanko04** [Dinomite-Studios/unity-azure-pipelines-tasks#99]
Hello,

I seem to have problems changing my project file names even with the correct settings.  After making the changes in the fields, my .exe and data folder still have the name of "drop."

![image](https://user-images.githubusercontent.com/25304444/63597030-26ddc800-c582-11e9-9776-7bb78811592f.png)

![image](https://user-images.githubusercontent.com/25304444/63597091-48d74a80-c582-11e9-98d3-fb0f8bf0a0be.png)

Thank you for your help!

-Tim

**Comment by FejZa** [comment]
Hi @tjanko04, I am sorry I was on vacation. Were you able to resolve the issue?

**Comment by tjanko04** [comment]
Hello,

Thank you so much for the reply.  I was out of the office as well, but yes, I am still experiencing the problem.  Here is my current build task setup:

In the images below, within the Unity Build Standalone task Output Filename as well as the Publish Artifact: Build Output task Artifact Name, I have “MQ-SCORE.”

[cid:image001.png@01D56D46.8867A5D0]

[cid:image002.png@01D56D46.8867A5D0]

However, while the folder output is correct, the .exe and _data folder still shows the default “drop.”

[cid:image007.png@01D56D46.8858FFD0]

Thanks for your help!

-Tim

**Comment by tjanko04** [comment]
Hello @FejZa ,

Is this project still active?

**Comment by FejZa** [comment]
Hi @tjanko04 yes it is. Just progressing slowly. But there is a new update coming in via PR soon adding log streaming to the tasks.

**Comment by tjanko04** [comment]
@FejZa Great, thank you for the update.  I'll keep any eye out!

**Comment by FejZa** [comment]
This is resolved in Build Task V3 and the just published extension update v2.7.
